# Generated by Django 4.2 on 2023-04-19 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Fakultet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': 'Fakultetlar',
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.IntegerField(default=10000, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=400, verbose_name='Ism, Familiya va Sharif')),
                ('group_number', models.CharField(max_length=20, verbose_name='Guruh')),
                ('status', models.CharField(choices=[('progress', 'Jarayonda'), ('confirmed', 'Tasdiqlangan'), ('not_confirmed', 'Tasdiqlanmagan'), ('closed', 'Yopildi')], default='progress', max_length=13)),
                ('file', models.ImageField(upload_to='ticket_image/', verbose_name='Kvitansiya rasmi')),
                ('telegam_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.faculty', verbose_name='Fakultet')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'db_table': 'ticket',
            },
        ),
    ]
