# Generated by Django 4.2 on 2023-04-30 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Fakultet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': 'Fakultetlar',
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ariza turi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ariza Turi',
                'verbose_name_plural': 'Ariza Turlari',
                'db_table': 'ticket_type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=400, verbose_name='Ism, Familiya va Sharif')),
                ('group_number', models.CharField(max_length=20, verbose_name='Guruh')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefon raqam')),
                ('telegam_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='apply.faculty', verbose_name='Fakultet')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('waiting', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan')], default='new', max_length=13)),
                ('file', models.ImageField(blank=True, null=True, upload_to='ticket_image/', verbose_name='Kvitansiya rasmi')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Ariza matni')),
                ('paynet', models.DecimalField(decimal_places=3, max_digits=9, verbose_name="To'langan summa")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='apply.tickettype', verbose_name='Ariza turi')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'db_table': 'ticket',
            },
        ),
    ]
