# Generated by Django 4.2 on 2023-05-04 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_ticket_user_alter_ticket_type_alter_user_faculty'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
