# Generated by Django 4.2 on 2023-05-04 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telegam_id',
            new_name='telegram_id',
        ),
    ]
